### ISSUE TITLE
vue3 引入canvas-select  启动后报错require is not defined

### ISSUE THREAD

**Issue by Promiseee** [heylight/canvas-select#140]
import CanvasSelect from "canvas-select";

export 'default' (imported as 'CanvasSelect') was not found in 'canvas-select' (module has no exports)

Uncaught runtime errors:
×
ERROR
require is not defined
ReferenceError: require is not defined
    at eval (webpack-internal:///./node_modules/canvas-select/lib/canvas-select.min.js:2:1)
    at ./node_modules/canvas-select/lib/canvas-select.min.js (http://localhost:8080/js/src_components_ImageListNew_vue.js:116:1)
    at __webpack_require__ (http://localhost:8080/js/app.js:177:32)
    at fn (http://localhost:8080/js/app.js:428:21)
    at eval (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/ImageListNew.vue?vue&type=script&scope=true&setup=true&lang=js:8:71)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/ImageListNew.vue?vue&type=script&scope=true&setup=true&lang=js (http://localhost:8080/js/src_components_ImageListNew_vue.js:18:1)
    at __webpack_require__ (http://localhost:8080/js/app.js:177:32)
    at fn (http://localhost:8080/js/app.js:428:21)
    at eval (webpack-internal:///./src/components/ImageListNew.vue?vue&type=script&scope=true&setup=true&lang=js:5:237)
    at ./src/components/ImageListNew.vue?vue&type=script&scope=true&setup=true&lang=js (http://localhost:8080/js/src_components_ImageListNew_vue.js:62:1)

**Comment by heylight** [comment]
1. 尝试升级一下vite
2. 直接cdn引用CanvasSelect

**Comment by Promiseee** [comment]
![image](https://github.com/user-attachments/assets/1989b65c-0fa5-4058-b563-185f9f58a5c7)
您好 请教一下 我的图片格式是 `data:image/png;base64,  报这个错是因为图片太大了吗

**Comment by Xigla** [comment]
感觉不像，你可以下载源码调试一下。index.html 里改下图片地址就行

**Comment by DongMenKant** [comment]
> ![image](https://private-user-images.githubusercontent.com/49059053/370629632-1989b65c-0fa5-4058-b563-185f9f58a5c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDQ0OTYsIm5iZiI6MTczNTU0NDE5NiwicGF0aCI6Ii80OTA1OTA1My8zNzA2Mjk2MzItMTk4OWI2NWMtMGZhNS00MDU4LWI1NjMtMTg1ZjlmNThhNWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA3MzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYWE4YWVhOWM0MGViNzUxMmJiNzRmNGMxODk2OWVlZWIyMzEyZjgyNDM4ZTY4M2Q3ZTU1OWM2MjhhM2NkODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c-Xlgb9AQpRPq9lw9dA2QL7r853fs7MYNevm__F6E1c) 您好 请教一下 我的图片格式是 `data:image/png;base64, 报这个错是因为图片太大了吗

是因为calcStep递归函数进入死循环了，可以增加return条件或递归次数限制来解决。如果是在项目组件中创建了CanvasSelect对象instance，记得在onBeforeUnmount时调用instance.destroy()进行销毁，即可避免。

**Comment by 309710274** [comment]
请问你这个问题解决了吗？我也碰到这个问题

**Comment by LiGang258** [comment]
> > ![image](https://private-user-images.githubusercontent.com/49059053/370629632-1989b65c-0fa5-4058-b563-185f9f58a5c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDQ0OTYsIm5iZiI6MTczNTU0NDE5NiwicGF0aCI6Ii80OTA1OTA1My8zNzA2Mjk2MzItMTk4OWI2NWMtMGZhNS00MDU4LWI1NjMtMTg1ZjlmNThhNWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA3MzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYWE4YWVhOWM0MGViNzUxMmJiNzRmNGMxODk2OWVlZWIyMzEyZjgyNDM4ZTY4M2Q3ZTU1OWM2MjhhM2NkODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c-Xlgb9AQpRPq9lw9dA2QL7r853fs7MYNevm__F6E1c) 您好 请教一下 我的图片格式是 `data:image/png;base64, 报这个错是因为图片太大了吗
> 
> 是因为calcStep递归函数进入死循环了，可以增加return条件或递归次数限制来解决。如果是在项目组件中创建了CanvasSelect对象instance，记得在onBeforeUnmount时调用instance.destroy()进行销毁，即可避免。

react项目里面 在清理函数里面使用instance.destroy();也无效啊
